language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    # Latest dependencies with all PHP versions
    - php: 7.2
    - php: 7.2
      env: COMPOSER_UPDATE_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.3
    - php: 7.3
      env: COMPOSER_UPDATE_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.4
    - php: 7.4
      env: COMPOSER_UPDATE_FLAGS='--prefer-lowest --prefer-stable'

      # Ignore the platform requirements for the upcoming PHP version
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs'
    - php: nightly
      env:
        - COMPOSER_FLAGS='--ignore-platform-reqs'
          COMPOSER_UPDATE_FLAGS='--prefer-lowest --prefer-stable --ignore-platform-reqs'
  allow_failures:
    - php: nightly
  fast_finish: true

branches:
  only:
    - master
    - develop

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction $COMPOSER_FLAGS
  - if [[ -n $COMPOSER_UPDATE_FLAGS ]]; then php composer.phar update $COMPOSER_UPDATE_FLAGS; fi

script:
  - mkdir -p build/logs;
  - composer unit-tests

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email:
    - danny.vandersluijs@icloud.com